### PR TITLE
Worked on app structure and made changes in all classes and functionsality

### PR DESCRIPTION
**Pull request by JoyLubega**
This pull request  has all of my flask implementation for this application covered.

Implemented features
-The app structure
-the functionality 
-config.py file
 please help and review my work
@CeciliaCaroline
@serubirikenny
@ruganda
@itrevex
@Sebuliba-Adrian
@LehruAJay_twitter

### CODE REVIEW

**Comment by JoyLubega** [comment]
please help and review my work
@CeciliaCaroline
@serubirikenny
@ruganda
@itrevex
@Sebuliba-Adrian
@LehruAJay_twitter

**Comment by itrevex** [comment]
Have really gone through but the badges are missing in your readme.md and you are not yet hosted on heroku

**Comment by JoyLubega** [comment]
am working on that now

**Comment by ruganda** [comment]
have reviewed you code. but it need more editing

**Comment by Sebuliba-Adrian** [comment]
I just reviewed your code. The folder structure is good. All you need is to
do is adding more tests and  removing  the word ...... list from  """Should
test if ___? has been created successfully""" on line 10 of your
file *shoppinglists_tests.py.
You should also consider .gitignore file on you next commits to avoid pushing the venv folder to your repo

**Comment by CeciliaCaroline** [comment]
Add more tests
More descriptive comments
Add badges
Add __pycache__ to gitignore
Add venv to gitignore
I think you should not merge your PR before reviewers have commented so that you apply their comments before merging to master

**Comment by JoyLubega** [comment]
thanks , i had that question about merging.

**Pull request merged**
